apps/tickets/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.AllTickets.as_view(), name="all-tickets"),
    path("create/", views.create_ticket, name="create-ticket"),
    path("<ticket_number>/", views.ticket_details, name="ticket-details"),
    path("<ticket_number>/assign", views.assign_ticket, name="assign-ticket"),
    path("<ticket_number>/update-status", views.update_ticket_status, name="update-status"),
    path("<ticket_number>/delete/attachment/<int:pk>/", views.delete_attachment, name="delete-attachment"),
]

djangodesk/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("user/", include("apps.users.urls")),
    path("tickets/", include("apps.tickets.urls")),
] + static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket_management/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("apps.core.urls")),
    path("user/", include("apps.users.urls")),
    path("tickets/", include("apps.tickets.urls")),
] + static(prefix=settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/tickets/models.py
import os

import magic
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse
from django.utils import timezone
from simple_history.models import HistoricalRecords

from ..users.models import User


class BaseModel(models.Model):
    created_at = models.DateTimeField(db_index=True, default=timezone.now)
    updated_at = models.DateTimeField(auto_now=True)

    # https://docs.djangoproject.com/en/4.2/topics/db/models/#abstract-base-classes
    class Meta:
        abstract = True


class Reference(models.Model):
    """Generate unique reference numbers for other models.

    The only purpose of this model is to generate unique reference numbers.
    """

    # Django models need at least 1 field
    created_date = models.DateTimeField(auto_now_add=True)

    @classmethod
    def generate(cls, prefix: str) -> str:
        """Generate a unique reference number prefixed with the provided prefix.

        For example, you could generate an invoice number as follows:

        Reference.generate(prefix="INV") # INV-0000001 etc.
        """

        instance = cls.objects.create()
        suffix = f"{instance.pk}".zfill(7)
        return f"{prefix}-{suffix}"


class Ticket(BaseModel):
    class Status(models.IntegerChoices):
        OPEN = 1, "Open"
        ASSIGNED = 2, "Assigned"
        IN_PROGRESS = 3, "In Progress"
        ON_HOLD = 4, "On Hold"
        RESOLVED = 5, "Resolved"
        CLOSED = 6, "Closed"

    class Priority(models.IntegerChoices):
        HIGH = "1", "High"
        MEDIUM = "2", "Medium"
        LOW = "3", "Low"

    class Type(models.IntegerChoices):
        SERVICE_REQUEST = 1, "Service Request"
        INCIDENT = 2, "Incident"
        PROBLEM = 3, "Problem"
        CHANGE_REQUEST = 4, "Change Request"

    ticket_number = models.CharField(max_length=25, unique=True, db_index=True)
    summary = models.CharField(max_length=100)
    description = models.TextField()
    issue_type = models.IntegerField(choices=Type.choices)
    assigned_agent = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.SET_NULL, related_name="assigned_tickets"
    )
    status = models.IntegerField(choices=Status.choices, default=Status.OPEN)
    priority = models.IntegerField(choices=Priority.choices, default=Priority.LOW)

    created_by = models.ForeignKey(
        User, null=True, blank=True, on_delete=models.SET_NULL, related_name="created_tickets"
    )
    completed_at = models.DateTimeField(null=True, blank=True)
    history = HistoricalRecords(cascade_delete_history=True)

    def __str__(self) -> str:
        return f"{self.ticket_number} - {self.summary}"

    def get_absolute_url(self):
        """This is used by django_tables2 to generate a link to the ticket detail page."""
        return reverse("ticket-details", kwargs={"ticket_number": self.ticket_number})

    def assign_agent(self, user: User):
        """This method accepts a User object, verifies it's role is either an admin or support agent and not the ticket
        author, then assigns it to the ticket's assigned agent field.

        Args:
            user (User): instance of user object that will be assigned to the ticket
        """
        if user.role == 1 or user.role == 2 and user != self.created_by:
            self.assigned_agent = user

    def set_status_open(self):
        "Sets the ticket status to Open. If an agent was already assigned to ticket, status will be Assigned instead."
        if self.assigned_agent:
            self.status = 2
            self._change_reason = f"Ticket has been reopened and reassigned to {self.assigned_agent}."
        else:
            self.status = 1
            self._change_reason = "Ticket has been reopened."

    def set_status_assigned(self):
        "Set the ticket status to Assigned."
        self.status = 2
        self._change_reason = f"Ticket has been assigned to {self.assigned_agent}."

    def set_status_in_progress(self):
        "Set the ticket status to In Progress."
        if self.status == 4:
            self._change_reason = "Work on the ticket has resumed."
        elif self.status == 2:
            self._change_reason = "Work on the ticket has started."
        else:
            self._change_reason = "Ticket is now In Progress."
        self.status = 3

    def set_status_on_hold(self):
        "Set the ticket status to On Hold."
        self.status = 4
        self._change_reason = "Ticket has been put on hold status."

    def set_status_resolved(self):
        "Set the ticket status to Resolved."
        self.status = 5
        self._change_reason = "Ticket has been resolved."

    def set_status_close(self):
        "Set the ticket status to Closed."
        self.status = 6
        self._change_reason = "Ticket has been closed."


class TicketComment(BaseModel):
    comment = models.TextField()
    ticket = models.ForeignKey(Ticket, null=True, on_delete=models.SET_NULL, related_name="comments")
    created_by = models.ForeignKey(User, null=True, on_delete=models.SET_NULL, related_name="comments")

    def __str__(self) -> str:
        return self.comment


def attachment_directory_path(instance, filename):
    return f"ticketfiles/{instance.ticket.id}/{filename}"


def validate_file_size(value):
    limit = 10 * 1024 * 1024  # 10 MB

    if isinstance(value, (list, tuple)):
        for file in value:
            if file.size > limit:
                raise ValidationError("File too large. Size should not exceed 10 MB.")
    else:
        if value.size > limit:
            raise ValidationError("File too large. Size should not exceed 10 MB.")


def validate_file_type(value):
    blacklisted_mime_types = ["application/x-msdownload", "application/x-dosexec", "application/CDFV2"]
    blacklisted_file_extensions = [".exe", ".msi", ".cmd", ".bat"]

    if isinstance(value, (list, tuple)):
        for file in value:
            file_mime_type = magic.from_buffer(file.read(2048), mime=True)
            ext = os.path.splitext(file.name)[1]
            if file_mime_type in blacklisted_mime_types or ext.lower in blacklisted_file_extensions:
                raise ValidationError("Unsupported file type.")
    else:
        file_mime_type = magic.from_buffer(value.read(2048), mime=True)
        if file_mime_type in blacklisted_mime_types:
            raise ValidationError("Unsupported file type.")


class TicketAttachment(BaseModel):
    attachment = models.FileField(
        upload_to=attachment_directory_path, validators=[validate_file_size, validate_file_type], null=True, blank=True
    )
    ticket = models.ForeignKey(Ticket, null=True, on_delete=models.CASCADE, related_name="attachments")

    def __str__(self) -> str:
        return self.attachment.name

    @property
    def attachment_name(self):
        return os.path.basename(self.attachment.name)

    @property
    def url(self):
        return self.attachment.url

    def delete(self, *args, **kwargs):
        super(TicketAttachment, self).delete(*args, **kwargs)
        self.ticket._change_reason = "File attachment was deleted from the ticket."
        self.ticket.save()

apps/tickets/forms.py
from django import forms
from django.forms import ModelForm

from .models import Ticket, TicketAttachment, TicketComment, validate_file_size


class TicketForm(ModelForm):
    # https://docs.djangoproject.com/en/4.2/topics/forms/modelforms/#overriding-the-default-fields
    class Meta:
        model = Ticket
        fields = ["summary", "issue_type", "description"]

        widgets = {
            "summary": forms.TextInput(attrs={"class": "form-control"}),
            "issue_type": forms.Select(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control"}),
        }

        labels = {
            "summary": "Ticket Summary (Required)",
            "description": "Description (Required)",
            "issue_type": "Issue Type (Required)",
        }

        error_class = "invalid-feedback"


class TicketCommentForm(ModelForm):
    class Meta:
        model = TicketComment
        fields = ["comment"]


# https://docs.djangoproject.com/en/5.0/topics/http/file-uploads/#uploading-multiple-files
class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput(attrs={"class": "form-control"}))
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class TicketAttachmentForm(ModelForm):
    def __init__(self, *args, **kwargs):
        self.max_files = 10
        if kwargs.get("file_count") is not None:
            self.file_count = kwargs.pop("file_count")
        if kwargs.get("new_ticket") is not None:
            self.new_ticket = kwargs.pop("new_ticket")
        super().__init__(*args, **kwargs)

    def clean_attachment(self):
        data = self.cleaned_data["attachment"]

        if not data and not self.new_ticket:
            raise forms.ValidationError("You did not choose any file to be uploaded.")

        if (len(data) + self.file_count) > self.max_files:
            raise forms.ValidationError(f"You can upload up to {self.max_files} files only.")

        return data

    class Meta:
        model = TicketAttachment
        fields = ["attachment"]

    attachment = MultipleFileField(
        label="Attachment (Add up to 10 files. Max file size: 10 MB):",
        validators=[validate_file_size],
    )

apps/tickets/templates/tickets/includes/add-comment-form.html
{% load widget_tweaks %}

 <!-- Add Comment Form -->
  <h5 class="pt-3 pe-5">Add Comment</h5>
  <form class="row g-3" method="POST" novalidate>
      {% csrf_token %}
      {% for form_field in comment_form %}
        {% if selected_ticket.status == 5 or selected_ticket.status == 6 %}
          {% render_field form_field class="form-control ticket-comment" placeholder="Adding comments is now disabled. Ticket is already resolved or closed." disabled="disabled" %}
          {{ form_field.errors }}
        {% else %}
          {% render_field form_field class="form-control ticket-comment" placeholder="Type your comment here" %}
          {{ form_field.errors }}
        {% endif %}
      {% endfor %}
      <button class="btn btn-primary" type="submit" name="add-comment" {% if selected_ticket.status == 5 or selected_ticket.status == 6 %}disabled{% endif %}>Submit</button>
  </form>
  <!-- End Comment Form -->

apps/tickets/templates/tickets/includes/agent-action-buttons.html
<!-- Enable Accept button if authenticated user is not ticket author, there's no assigned agent yet, and ticket status is Open -->
{% if request.user != selected_ticket.created_by and not selected_ticket.assigned_agent and selected_ticket.status == 1 %}

  <a href="#" class="btn btn-success btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#AcceptTicketModal">
    <i class="bi bi-check-circle"></i> Accept
  </a>

  <!-- Accept Ticket Modal -->
  {% include "tickets/includes/modals/accept-ticket-modal.html" %}

{% elif request.user == selected_ticket.assigned_agent %}

  <!-- Enable Resolve/Close buttons if ticket status is In-Progress -->
  {% if selected_ticket.status == 3 %}
    <a href="#" class="btn btn-success btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#ResolveTicketModal">
      <i class="bi bi-check-circle"></i> Resolve
    </a>
    <a href="#" class="btn btn-danger btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#CloseTicketModal">
      <i class="bi bi-x-circle"></i> Close
    </a>

    <a href="#" class="btn btn-secondary btn-sm mt-1"><i class="bi bi-arrow-right-circle"></i> Transfer</a>
  {% endif %}

  {% if selected_ticket.status == 2 %}
    <a href="#" class="btn btn-success btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#StartTicketModal">
      <i class="bi bi-play-circle"></i> Start Work
    </a>
  {% elif selected_ticket.status != 4 and selected_ticket.status != 5 and selected_ticket.status != 6 %}
    <a href="#" class="btn btn-warning btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#OnHoldTicketModal">
      <i class="bi bi-pause-circle"></i> On Hold
    </a>
  {% elif selected_ticket.status == 4 %}
    <a href="#" class="btn btn-warning btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#ResumeTicketModal">
      <i class="bi bi-play-circle"></i> Resume
    </a>
  {% endif %}


  <!-- Enable reopen button if ticket status is either Closed or Resolved -->
  {% if selected_ticket.status == 5 or selected_ticket.status == 6 %}
    <a href="#" class="btn btn-danger btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#ReopenTicketModal">
      <i class="bi bi-arrow-counterclockwise"></i> Reopen
    </a>
  {% endif %}
  
  <!-- Start Ticket Modal -->
  {% include "tickets/includes/modals/start-ticket-modal.html" %}

  <!-- Close Ticket Modal -->
  {% include "tickets/includes/modals/close-ticket-modal.html" %}

  <!-- Resolve Ticket Modal -->
  {% include "tickets/includes/modals/resolve-ticket-modal.html" %}

  <!-- Reopen Ticket Modal -->
  {% include "tickets/includes/modals/reopen-ticket-modal.html" %}

  <!-- On Hold Ticket Modal -->
  {% include "tickets/includes/modals/on-hold-ticket-modal.html" %}

  <!-- Resume Ticket Modal -->
  {% include "tickets/includes/modals/resume-ticket-modal.html" %}
{% endif %}

apps/tickets/templates/tickets/includes/comment-section.html
{% load static %}

<hr class="">
{% if request.user == selected_ticket.created_by or request.user == selected_ticket.assigned_agent %}
  {% include "tickets/includes/add-comment-form.html" %}
{% endif %}

<!-- All Comment Section -->
<h5 class="mt-5">All Comments</h5>

{% for comment in ticket_comments %}
<div class="card">
  <div class="card-comment">
    <div class="comment-header">
      {% if comment.created_by %}
        <img src="{% if comment.created_by.avatar %}{{ comment.created_by.avatar.url }}{% else %}{% static "img/profile.png" %}{% endif %}"
        alt="Profile"
        class="rounded-circle asignee-avatar"/>
      {% endif %}

      {% if comment.created_by.get_full_name %}
        {{ comment.created_by.get_full_name }}
      {% else %}
        {{ comment.created_by }}
      {% endif %}

      <span class="mx-1">&bullet;</span>
      {{ comment.created_at }}
    </div>

    <div class="mt-3">
      {{ comment }}
    </div>

  </div>
</div>

{% empty %}
<div class="card-comment">
  <div>There are no comments yet.</div>
</div>
{% endfor %}
<!-- End Comment Section -->

apps/tickets/templates/tickets/includes/ticket-activity-section.html
<hr class="">
<h5 class="pt-3 pe-5">Recent Activity</h5>

  <section class="py-3">
    <ul class="timeline">
      {% for h in selected_ticket.history.all %}
        <li class="timeline-item mb-3 {% if h.status == 1 %}timeline-item-open{% elif h.status == 2 or h.status == 3 or h.status == 4 %}timeline-item-progress{% elif h.status == 5 or h.status == 6 %}timeline-item-closed{% endif %}">
          <div class="">{{ h.history_change_reason }}</div>
          <div class="text-muted mb-2 timeline-header">{{ h.history_user }} <span class="mx-1">&bullet;</span> {{ h.history_date }}</div>
        </li>
      {% endfor %} 
    </ul>
  </section>

<!-- Section: Timeline -->

<!-- Section: Timeline -->

apps/tickets/templates/tickets/includes/ticket-details-section.html
{% load static %}

<hr class="d-lg-none">

<div class="mb-2">
  <h5 class="card-title">Details</h5>
  <div class="badge rounded-pill text-bg-{% if selected_ticket.status == 1 %}danger{% elif selected_ticket.status == 2 or selected_ticket.status == 3 or selected_ticket.status == 4 %}warning{% elif selected_ticket.status == 5 or selected_ticket.status == 6 %}success{% endif %}">
    {{ selected_ticket.get_status_display }}
  </div>
  <div class="mt-3"><span class="fw-semibold">Last updated: </span><i class="bi bi-calendar"></i> {{ selected_ticket.updated_at|date:"m/d/Y g:i A" }}</div>
  <div class="mt-3"><span class="fw-semibold">Created on: </span><i class="bi bi-calendar"></i> {{ selected_ticket.created_at|date:"m/d/Y g:i A" }}</div>
  {% if selected_ticket.created_by.department %}
    <div class="mt-3"><span class="fw-semibold">Department: </span>{{ selected_ticket.created_by.department }}</div>
  {% endif %}

</div>

<hr class="">

<div class="mb-2">
  <h5 class="card-title pt-1">Assignees:</h5>
  {% if selected_ticket.assigned_agent %}
  <img src="{% if selected_ticket.assigned_agent.avatar %}{{ selected_ticket.assigned_agent.avatar.url }}{% else %}{% static "img/profile.png" %}{% endif %}" alt="Profile" class="rounded-circle asignee-avatar" />
  {% endif %}
  {{ selected_ticket.assigned_agent.get_full_name }}
</div>

<hr class="">

<div class="mb-2">
  <h5 class="card-title pt-1">Created By:</h5>
  {% if selected_ticket.created_by %}
  <img src="{% if selected_ticket.created_by.avatar %}{{ selected_ticket.created_by.avatar.url }}{% else %}{% static "img/profile.png" %}{% endif %}" alt="Profile" class="rounded-circle asignee-avatar" />
  {% endif %}
  {{ selected_ticket.created_by.get_full_name }}
</div>

<hr class="">

<div class="mb-2">
  <h5 class="card-title pt-1">Contact Details</h5>
  <div class="mt-3"><span class="fw-semibold">Email: </span>{{selected_ticket.created_by.email}}</div>
  <div class="mt-3"><span class="fw-semibold">Phone: </span>{{selected_ticket.created_by.phone}}</div>
</div>

apps/tickets/templates/tickets/includes/ticket-filter-form.html
{% load widget_tweaks %}

<div class="accordion" id="accordionFlushExample">

  <div class="accordion-item">
    <h2 class="accordion-header">
      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
        Filters
      </button>
    </h2>
    <div id="flush-collapseOne" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">

      <div class="accordion-body">

        <form hx-get="{% url "all-tickets" %}" hx-target="div.table-container" hx-swap="outerHTML" hx-indicator=".progress" class="form-inline row g-3">

            <div class="col-lg-2 col-md-12">
              <div class="form-floating">
                {% render_field filter_form.ticket_number class="form-control" id="floatingTicket" placeholder="Ticket Number" %}
                <label for="floatingTicket">Ticket Number</label>
              </div>
            </div>

            <div class=" col-lg-2 col-md-12">
              <div class="form-floating">
                {% render_field filter_form.summary class="form-control" id="floatingSummary" placeholder="" %}
                <label for="floatingSummary">Summary</label>
              </div>
            </div>

            <div class=" col-lg-2 col-md-12">
              <div class="form-floating">
                {% render_field filter_form.issue_type class="form-control" id="floatingIssueType" aria-label="Issue Type" %}
                <label for="floatingIssueType">Issue Type</label>
              </div>
            </div>

            <div class=" col-lg-2 col-md-12">
              <div class="form-floating">
                {% render_field filter_form.status class="form-control" id="floatingStatus" aria-label="Status" %}
                <label for="floatingStatus">Status</label>
              </div>
            </div>

            <div class=" col-lg-2 col-md-12">
              <div class="form-floating">
                {% render_field filter_form.created_at class="form-control" id="floatingDate" aria-label="Created At" %}
                <label for="floatingDate">Created At</label>
              </div>
            </div>

            {% if request.user.role != 3 %}
              <div class="col-lg-2 col-md-12">
                <div class="form-floating">
                  {% render_field filter_form.created_by class="form-control" id="floatingTicket" placeholder="Created By" %}
                  <label for="floatingTicket">Created By</label>
                </div>
              </div>
            {% endif %}

            <div class="col-lg-2 col-md-12">
              <div class="form-floating">
                {% render_field filter_form.assigned_agent class="form-control" id="floatingTicket" placeholder="Assigned Agent" %}
                <label for="floatingTicket">Assigned Agent</label>
              </div>
            </div>

            <div class="col-lg-4 col-md-12">
                <button type="submit" class="btn btn-primary btn-sm p-3" name="ticket-filter">Submit</button>
                <button type="reset" class="btn btn-secondary btn-sm p-3">Reset</button>
            </div>

        </form>

      </div>

    </div>

  </div>

</div>

apps/tickets/templates/tickets/includes/ticket-summary-section.html
<h3 class="pt-3 pe-5">Summary: {{ selected_ticket.summary }}</h3>

<!-- Ticket Action Buttons -->
{% if request.user.role != 3 %}
  {% include "tickets/includes/agent-action-buttons.html" %}
{% endif %}

{% if request.user == selected_ticket.created_by %}
  {% include "tickets/includes/user-action-buttons.html" %}
{% endif %}

<hr class="mt-3 d-none d-lg-block">

<!-- Attachment List -->
<div class="mt-4"><span class="fw-semibold">Attachments: </span>
  {% for attachment in selected_ticket.attachments.all %}
    <span class="text-bg-secondary rounded me-1 attachment-badge fw-bold">
      <a href="{{ attachment.url }}" target="_blank" class="attachment-label">
        {{ attachment.attachment_name }}
      </a>

      <!-- Enable delete attachment option if authenticated user is ticket author, and ticket status is not Closed or Resolved -->
      {% if request.user == selected_ticket.created_by and selected_ticket.status != 5 and selected_ticket.status != 6 %}
        <!-- Delete Attachment trigger modal -->
        <a href="#" data-bs-toggle="modal" data-bs-target="#attachment{{ attachment.id }}Modal">
          <i class="bi bi-x-lg delete-attachment-label"></i>
        </a>
      {% endif %}
    </span>

      <!-- Delete Attachment Modal -->
      {% include "tickets/includes/modals/delete-attachment-modal.html" %}

  {% empty  %}
    No attachment

  {% endfor %}

</div>

<div class="mt-4 pe-5"><span class="fw-semibold">Issue Type: </span>{{ selected_ticket.get_issue_type_display }}</div>
<div class="mt-3 pe-5"><span class="fw-semibold">Description: </span>{{ selected_ticket.description }}</div>

apps/tickets/templates/tickets/includes/upload-attachment-modal.html
<div class="modal fade" id="AddAttachmentModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Upload Files</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>

        <form class="row g-3" method="POST" enctype="multipart/form-data" novalidate>
            {% csrf_token %}

            <div class="modal-body">
                <div class="col-12">
                <label class="form-label">{{ attachment_form.attachment.label }}</label>
                {{ attachment_form.attachment }}
                {% for field, error in attachment_form.errors.items %}
                {{ error }}
                {% endfor %}
                </div>
            </div>

            <div class="modal-footer">
                <a href="#" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</a>
                <button type="submit" class="btn btn-primary" name="add-attachment">Upload</button>
            </div>

        </form>
    </div>
    </div>
</div>

apps/tickets/templates/tickets/includes/user-action-buttons.html
<!-- Enable if ticket status is Closed or Resolved -->
{% if selected_ticket.status == 5 or selected_ticket.status == 6 %}
<a href="#" class="btn btn-danger btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#ReopenTicketModal">
  <i class="bi bi-arrow-counterclockwise"></i> Reopen
</a>
{% endif %}

<!-- Enable Close ticket and Attach buttons if ticket status is not Closed or Resolved -->
{% if selected_ticket.status != 5 and selected_ticket.status != 6 %}
  <a href="#" class="btn btn-danger btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#CloseTicketModal">
    <i class="bi bi-x-circle"></i> Close
  </a>
  <a href="#" class="btn btn-primary btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#AddAttachmentModal">
    <i class="bi bi-paperclip"></i> Attach
  </a>
  <a href="#" class="btn btn-primary btn-sm mt-1" data-bs-toggle="modal" data-bs-target="#EditTicketModal"><i class="bi bi-pencil-square"></i> Edit</a>

{% endif %}

<!-- Upload Attachment Modal -->
{% include "tickets/includes/modals/upload-attachment-modal.html" %}

<!-- Edit Ticket Modal -->
{% include "tickets/includes/modals/edit-ticket-modal.html" %}

<!-- Close Ticket Modal -->
{% include "tickets/includes/modals/close-ticket-modal.html" %}

<!-- Reopen Ticket Modal -->
{% include "tickets/includes/modals/reopen-ticket-modal.html" %}